### ISSUE TITLE
Questions: Comparsion with panoptic_mapping

### ISSUE THREAD

**Issue by Kin-Zhang** [ethz-asl/3d_vsg#1]
Since you are also the authors of panoptic_mapping, I'm curious about what's the performance difference between 3d_vsg and panoptic_mapping in the semantic results and long-term change comparison.

**Comment by Schmluk** [comment]
Hi @Kin-Zhang 

Thank you for this observation! Panoptic Mapping and 3D VSG tackle two different, but related problems. In Panoptic Mapping we detect the past changes in a scene during online mapping. This leads to a map representation that is consistent w.r.t. *past* changes. In 3D VSG we predict which *future* changes are likely to guide the robot. Hope this helps, let us know if you have more questions!
