### ISSUE TITLE
dataset and training issue

### ISSUE THREAD

**Issue by xz-123-new** [ethz-asl/3d_vsg#4]
there is no src.scripts.generate_dataset under scripts to generate data , and when running python -m src.scripts.train_variability, it occurs that raise Exception("Raw File List Not Found"), which means there is no raw_files.txt under raw file, but i don't konw where to find it or how to generate, could you help me with these two problems, thanks!

**Comment by Schmluk** [comment]
Thank you for pointing this out! Should be fixed as of #5 .
